export const dummyOrders = [
  {
    orderId: "ORD1001",
    customerName: "Rahul Sharma",
    phone: "9876543210",
    email: "rahul@example.com",
    address: "12/B, MG Road, Delhi",
    pincode: "110001",
    productName: "Pain Relief Tablets",
    quantity: 2,
    totalAmount: 499,
    status: "Pending",
    paymentStatus: "Pending",
    paymentMode: "COD",
    agentName: "Agent 1",
    createdAt: "2025-01-10",
    remarks: "Customer requested evening delivery."
  },
  {
    orderId: "ORD1002",
    customerName: "Priya Verma",
    phone: "9123456780",
    email: "priya.v@example.com",
    address: "Flat 402, Sea View, Mumbai",
    pincode: "400001",
    productName: "Vitamin C Capsules",
    quantity: 1,
    totalAmount: 850,
    status: "Delivered",
    paymentStatus: "Paid",
    paymentMode: "Online",
    agentName: "Agent 3",
    createdAt: "2025-01-11",
    remarks: ""
  },
  {
    orderId: "ORD1003",
    customerName: "Amit Kumar",
    phone: "8885551234",
    email: "amit.k@test.com",
    address: "Sector 18, Noida",
    pincode: "201301",
    productName: "Protein Powder",
    quantity: 1,
    totalAmount: 2400,
    status: "Shipped",
    paymentStatus: "Paid",
    paymentMode: "Online",
    agentName: "Agent 1",
    createdAt: "2025-01-12",
    remarks: "Urgent delivery."
  },
  {
    orderId: "ORD1004",
    customerName: "Rahul Sharma",
    phone: "9876543210",
    email: "rahul@example.com",
    address: "12/B, MG Road, Delhi",
    pincode: "110001",
    productName: "Pain Relief Tablets",
    quantity: 2,
    totalAmount: 499,
    status: "Pending",
    paymentStatus: "Pending",
    paymentMode: "COD",
    agentName: "Agent 1",
    createdAt: "2025-01-10",
    remarks: "Customer requested evening delivery."
  },
  {
    orderId: "ORD1005",
    customerName: "Priya Verma",
    phone: "9123456780",
    email: "priya.v@example.com",
    address: "Flat 402, Sea View, Mumbai",
    pincode: "400001",
    productName: "Vitamin C Capsules",
    quantity: 1,
    totalAmount: 850,
    status: "Delivered",
    paymentStatus: "Paid",
    paymentMode: "Online",
    agentName: "Agent 3",
    createdAt: "2025-01-11",
    remarks: ""
  },
  {
    orderId: "ORD1006",
    customerName: "Amit Kumar",
    phone: "8885551234",
    email: "amit.k@test.com",
    address: "Sector 18, Noida",
    pincode: "201301",
    productName: "Protein Powder",
    quantity: 1,
    totalAmount: 2400,
    status: "Shipped",
    paymentStatus: "Paid",
    paymentMode: "Online",
    agentName: "Agent 1",
    createdAt: "2025-01-12",
    remarks: "Urgent delivery."
  }
];