export const leads = [
  {
    _id: "1",
    name: "Rahul Sharma",
    role: "CEO, TechFlow",
    phone: "+91 98765 43210",
    email: "rahul@techflow.com",
    service: "Website Dev",
    value: "₹45,000",
    status: "Follow Up",
    lastActivity: "2h ago",
    owner: "Amit V.",
  },
  {
    _id: "2",
    name: "Sneha Patel",
    role: "Marketing Head",
    phone: "+91 98765 01234",
    email: "sneha@marketing.io",
    service: "SEO Package",
    value: "₹25,000",
    status: "Won",
    lastActivity: "1d ago",
    owner: "Rohit S.",
  },
  {
    _id: "3",
    name: "Manish Gupta",
    role: "Freelancer",
    phone: "+91 99887 76655",
    email: "manish@gmail.com",
    service: "App Dev",
    value: "₹1,20,000",
    status: "Lost",
    lastActivity: "3d ago",
    owner: "Amit V.",
  },
  {
    _id: "4",
    name: "Priya Singh",
    role: "Founder, StyleHub",
    phone: "+91 91234 56789",
    email: "priya@stylehub.com",
    service: "E-commerce",
    value: "₹85,000",
    status: "New",
    lastActivity: "10m ago",
    owner: "Admin",
  },
];
